name: Todo List
on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  build: 
    env: 
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Run tests 
        env: 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: npm run test



  
   